Repository artsy/forque, pull requests merged in 2022-03, with the labels that each got.

#19 feat: expand debug pages to show publicRuntimeConfig
  src/pages/env/index.page.tsx
  src/pages/env/server.page.tsx
Labels: Squash On Green

#24 fix(env): force landing page to be ssr, to load runtime env
  src/pages/index.page.tsx
Labels: Squash On Green

#25 Update pattern for prettier
  package.json
Labels: Squash On Green

#27 feat(auth): add relay authentication; fix initial login flash
  src/__generated__/ArtistSlugQuery.graphql.ts
  src/__generated__/pagesQuery.graphql.ts
  src/components/Layout.tsx
  src/pages/_app.page.tsx
  src/pages/artist/[artistSlug].page.tsx
  src/pages/index.page.tsx
  src/system/artsy-next-auth/auth/api.ts
  src/system/artsy-next-auth/auth/cookies.ts
  src/system/artsy-next-auth/auth/user.ts
  src/system/relay/fetchRelayData.ts
  src/system/relay/middleware.ts
  src/system/relay/setupEnvironment.ts
Labels: Squash On Green

#34 feat(system): add SystemContext for system-level functions
  src/hooks/useMutation.ts
  src/pages/_app.page.tsx
  src/system/SystemContext.tsx
  src/system/relay/setupEnvironment.ts
Labels: hackathon

#40 fix(relay): Properly configure relay network
  src/system/relay/setupEnvironment.ts
Labels: hackathon

#42 ci(test): add --runInBand to fix timeouts
  .circleci/config.yml
  jest.config.js
  jest.setup.js
  package.json
Labels: Squash On Green, hackathon

#43 chore(testing): fix test type-checking; add type-check job to CI
  .circleci/config.yml
  src/pages/uploads/[key].page.tsx
  src/pages/uploads/utils/filesize.ts
  tsconfig.json
Labels: hackathon

#44 fix(relay): yet again, properly initialize env
  src/system/relay/setupEnvironment.ts
Labels: hackathon

#45 fix(dedupe): force ssr on subpage
  src/pages/artists/dedupe/[slug].page.tsx
  src/pages/artists/dedupe/index.page.tsx
Labels: Squash On Green

#46 fix(loader): cleanup
  src/system/RouteLoadingBar.tsx
Labels: Squash On Green

#48 feat: Wire up the 3 basic user fields
  data/schema.graphql
  src/__generated__/UserIdQuery.graphql.ts
  src/__generated__/useUpdateUserMutation.graphql.ts
  src/pages/users/[userId].page.tsx
Labels: hackathon
